quickstart.html, src/quickstart.pug
Since release 0.3.3 of the Karma runner, it is capable of re-using the Karma configuration file. Mention this in the Quickstart guide.
=> doc(faq): Update Quickstart guide for Karma runner

index.html, src/index.pug, stylesheets/stryker.css
First draft of adding an example and output paragraph to the index.
Code examples need to be fixed.
=> Extend index page with example and clear text reporter example output

src/stryker4s/quickstart.pug
Some documentation in the Stryker4s quickstart was a bit outdated. This fixes that.
Also, it's a bit annoying having to update the handbook in two places 😁
=> Fix incorrect Stryker4s quickstart documentation

src/stryker4s/index.pug
A small button to link to the roadmap.
This is a fast version which i my opinion might be replaced by #107 if we wanted that.
=> Add link to roadmap for Stryker4s

src/scss/all.scss, src/scss/bootstrap.scss
I've changed the SASS bootstrap imports to only use what's needed, instead of everything from bootstrap. This changes the created CSS size from 126KB to 79KB, meaning visitors can start killing mutants even faster!
=> Import only used bootstrap dependencies

src/index.pug
On the main page, at the Features bit, I noticed there's a small error on certain device sizes. This fixes that by having all 'Features' in 1 row and just letting Bootstrap and flex-box handle the sizing.
Before:
After:
=> Fix Features responsiveness

src/stryker4s/quickstart.pug
Change some text to no longer indicate on how you can configure log levels in de config (since that's removed). Instead, I refer to our up to date configuration page.
=> Update quick-start on how to configure log levels

src/blog.pug, src/example.pug, src/index.pug, src/layout/section-layout.pug, src/scss/stryker/links.scss, src/stryker-net/quickstart.pug, src/stryker/quickstart.pug, tasks/markdown-it.js
As proposed in #123. Adds a small clickable icon when hovering a heading. Clicking that icon updates the URL to point to that section. It looks like this:
This also adds a custom function to generate pretty slugs. Instead of `#but-wait%2C-what-about-code-coverage%3F` we now get `#but-wait-what-about-code-coverage` 🙂
=> feat: add permalinks to section headings

src/scss/stryker/fork-me-banner.scss
Before:
After:
Spacing is now the same on both sides. It annoyed me
=> Fix "View me on GitHub" icon margin

src/blog/2020-10-07/announcing-stryker-4-mutation-switching.pug
The Stryker 4 announcement blog post contained several sentences with duplicate words.
The last sentence did not contain a duplicate word, but was an odd structure;
Don't worry we will make sure we will let you know, vs, Don't worry we will make sure to let you know
=> Stryker 4 announcement sentence fixes

.github/workflows/release.yml
In preparation for the new site, we should be able to release manually to make it easy to revert the test release(s)
=> Support manually releasing

docs/General/dashboard.md
When we are in the https://stryker-mutator.io/docs/General/dashboard
The link generated is `https://dashboard.stryker-mutator.io./`
=> Fix the link

package.json
When auditing the docs inplace, your local changes get reverted if you use `npm start` again. 😔
This change will makes sure the clone only happens once during the install phase.
=> chore(clone): only clone postinstall

sidebars.js
Allow for a custom sidebar to be defined per repository.
The `sidebar.json` (or `sidebar.js` if you prefer a node module) should contain a valid [sidebar object](https://v2.docusaurus.io/docs/docs-introduction#sidebar-object). The document root is part of the URL, so [document ids](https://v2.docusaurus.io/docs/docs-introduction#document-id) should be prefixed with the repository name.
=> feat(sidebar): allow for a custom sidebar per repo

docusaurus.config.js
[Docusaurus supports something](https://v2.docusaurus.io/docs/search/) called [DocSearch](https://docsearch.algolia.com/) which is a service that indexes a documentation website every 24 hours and creates a search bar to put on the website. I've requested this for the stryker-mutator.io website (under the strykermutator.npa@gmail.com email). It supports search of both headers and deep text and it looks a little something like this:
I've created a little demo video here: https://imgur.com/a/ctLok7U
It also supports a dedicated search page for more results:
The API key should be public as it is should be included in a script in the website.
=> feat: add docsearch

docs/General/dashboard.md
https://github.com/stryker-mutator/mutation-testing-elements/tree/master/packages/mutation-testing-report-schema → https://github.com/stryker-mutator/mutation-testing-elements/tree/master/packages/report-schema
=> Fix broken "mutation testing report schema" links

src/pages/index.js
The link from the logo on the front page goes to the correct page
=> Fix link to CSharp introduction in index.js

docs/General/dashboard.md
Now that https://github.com/stryker-mutator/stryker-net/pull/1663 is merged and Stryker.NET v1.0 is released, the .NET implementation is able to automatically retrieve the `project` and `version` if the project being mutated is using [SourceLink](https://github.com/dotnet/sourcelink).
=> Update the Stryker.NET `project` and `version` truth table

blog/2018-10-06-mutation-switching.md
Fixes a small mistake on the [Mutation switching in Stryker4s](https://stryker-mutator.io/blog/mutation-switching/#:~:text=be%20mutated%20to-,there,-counterparts.%20This%20would) blog.
=> Fix grammar

docs/General/example.mdx
The __step 7__ in [the example](https://stryker-mutator.io/docs/General/example/) to run mutations testing with Stryker suggests to run `npm run stryker`. Altho, the `stryker` script has been renamed to `test:mutation` in [this commit](https://github.com/stryker-mutator/robobar-example/commit/9699ff5d39e9fe8559cbda2b546872dca1b94fa3#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L13-R18) leading to the following error when blindly following the steps:
```shell
npm ERR! Missing script: "stryker"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```
This pull request updates the example to use `npm run test:mutation` instead.
=> fix(docs): update example mutation testing command

docs/General/example.mdx
Hello guys! I found this project during the current hacktoberfest and decided to give it a shot and try contributing to it.
So, this is a simple PR with 2 minor improvements in the example doc:
1. I made the location of the test coverage file more specific in step 6 of the "Try it yourself" section. I make this change because when I was reading this part, I had some confusion to find which was the correct test coverage file that was being referred to by the documentation.
2. I added the command `git reset --hard` at the beginning of the commands section "Try to install stryker yourself". That's because the website commands are intended to be direct and not leave anyone lost, however, `git checkout` does not work directly for those who came to this command reading and doing the tutorial. …
=> Minor improvements in example doc

docusaurus.config.js, package-lock.json, package.json
Speed up build using `swc` as recommended for larger repo's (for example the [docusaurus website itself](https://github.com/facebook/docusaurus/blob/main/website/docusaurus.config.js#L104-L120)). 
16% faster than the default (babel) and _slightly_ faster than esbuild for clean builds.
For cached (or subsequent builds, dev mode etc) it's already fairly fast, but swc still wins out:
=> build: use swc-loader to speed up build
