- javascripts/main.js
stryker-karma will 404 in the npm repository, it's called stryker-karma-runner
> Change stryker-karma to stryker-karma-runner

- Gruntfile.js
- package.json
feat(build): Add build task to update contributors
> feat(build): Automate release tasks

- quickstart.html
> docs(quickstart) Fix a typo

- package.json
The existing `grunt test` didn't work, there seem to be no tests for the website.
> chore(site): Make it easier to preview changes

- plugins.html
- src/plugins.pug
Could you look at this @mthmulders ?
_I didn't have the time to add it to the quickstart right now. But we should do that in the future as well._
EDIT: nevermind, Jest is already on the quickstart page.
> Add stryker-jest-runner to the Plugins page

- faq.html
- src/faq.pug
Clarify the score calculation based on https://github.com/stryker-mutator/stryker/pull/309
> Clarify score calculation

- CONTRIBUTING.md
- README.md
- package.json
Add contributing guide in order to welcome newcomers and help them create good PR's
Add readme pointing to the contributing guide.
> docs(contributing): Add contributing guide

- src/stryker4s/index.pug
fixes #92 
Hopefully, these texts are a bit better. Grammer is sadly not my strongest quality.
> Fix spelling errors on stryker4s index page

- src/fillViewModel.js
- src/layout/section-layout.pug
- src/stryker/index.pug
> Clarify stryker for js and friends

- src/blog/2018-12-25/blog.json
- src/blog/2018-12-25/stryker4s-0-1-0-released.pug
Added a blog for the new Stryker4s 0.1.0 release.
@nicojs @legopiraat If you could have a look that'd be great!
> Blog: Stryker4s 0.1.0 released

- CONTRIBUTING.md
> docs(contributing.md): Document new way of working

- src/stryker-net/quickstart.pug
update documentation to reflect configuration parameters name change and add new parameters
> fix documentation about config for stryker-net

- src/blog/2019-03-15/announcing-dotnet-framework-support.pug
A full rewrite of the blog article. 
It had all the content in it, but it wasn't a coherent article INMHO. I've rewritten it and removed some confusing things. It still needs some love (especially the "Start using Stryker.NET" part), but I would need to talk to @richardwerkman or @Mobrockers for that.
> Rewrite the blog article

- src/stryker4s/quickstart.pug
Changing versions in multiple places is hard 😣
Same badge as in our readme: https://github.com/stryker-mutator/stryker4s/blob/master/README.md
> Replace stryker4s quickstart version with dynamic badge

- src/scss/stryker/links.scss
> Replace external link with fontawesome icon

- src/blog/2020-10-07/announcing-stryker-4-mutation-switching.pug
- src/blog/2020-10-07/blog.json
- src/stryker/plugins.pug
- Prepare plugin section for stryker 4.0
- Add blog article for Stryker 4
> Add blog article for Stryker 4.0

- src/blog/2020-10-07/announcing-stryker-4-mutation-switching.pug
Should fix the rendering of this link:
> Fix link rendering

- src/blog/2020-05-15/azure-pipelines-integration.pug
Example pipeline syntax does not currently work
> fix git diff pipeline example

- docusaurus.config.js
- Respect users set color-scheme to set default theme
- Add meta image for nicer link previews
> feat(metadata): improve page metadata

- docusaurus.config.js
> docs: add prism light theme

- docusaurus.config.js
> Update announcement bar to 'Scala Love in the City' talk

- blog/2019-04-05-announcing-dotnet-framework-support.md
- legacy-redirects.js
Reverts stryker-mutator/stryker-mutator.github.io#316
> Revert "Update legacy-redirects.js"

- docusaurus.config.js
> chore: add trailingSlash: false

- blog/2022-09-06-announcing-incremental-mode.md
> blog(incremental): add blog about incremental
